version: '3.8'

networks:
  ev_net:
    external: true # Usa la red creada por el otro compose

services:
  # --- CP 1 (ALC1) ---
  cp1_engine:
    build: .
    container_name: cp1_engine
    networks:
      - ev_net
    command: >
      python ev_cp/EV_CP_E.py
      --socket-port 6001
      --kafka-broker kafka:9093

  cp1_monitor:
    build: .
    container_name: cp1_monitor
    depends_on: [cp1_engine]
    networks:
      - ev_net
    command: >
      python ev_cp/EV_CP_M.py
      --cp-id ALC1
      --central-ip ev_central
      --central-port 8000
      --registry-ip ev_registry
      --registry-port 6000
      --engine-ip cp1_engine
      --engine-port 6001

  # --- CP 2 (MAD1) ---
  cp2_engine:
    build: .
    container_name: cp2_engine
    networks:
      - ev_net
    command: >
      python ev_cp/EV_CP_E.py
      --socket-port 6002
      --kafka-broker kafka:9093

  cp2_monitor:
    build: .
    container_name: cp2_monitor
    depends_on: [cp2_engine]
    networks:
      - ev_net
    command: >
      python ev_cp/EV_CP_M.py
      --cp-id MAD1
      --central-ip ev_central
      --central-port 8000
      --registry-ip ev_registry
      --registry-port 6000
      --engine-ip cp2_engine
      --engine-port 6002